package io.github.masamune.util

import java.io.File
import java.io.FileInputStream
import java.util.*

fun main() {
    val bundleFile = File("../assets/ui/messages.properties")
    val targetPackage = "io.github.masamune.ui.model"
    val className = "I18NKey"
    val i18nKeyFile = File("../core/src/main/kotlin/${targetPackage.replace(".", "//")}/$className.kt")
    val resourceBundle = PropertyResourceBundle(FileInputStream(bundleFile))

    println("Processing i18n bundle file at ${i18nKeyFile.absolutePath}.")
    val content = buildString {
        append("package $targetPackage").appendLine().appendLine()
        append("import com.badlogic.gdx.utils.I18NBundle").appendLine().appendLine()
        append("// This is an autogenerated class by gradle's 'genI18nKeys' task. Do not touch it!").appendLine()
        append("enum class $className(val key: String) {").appendLine()

        resourceBundle.keySet().sorted().forEach { key ->
            var data = key.trim()
            if (data.isNotEmpty()) {
                data = data.replace(".", "_")
                data = data.replace("[A-Z]".toRegex()) { "_" + it.value.first().lowercase() }

                append("    ")
                append(data.uppercase())
                append("(\"$key\")")
                append(",")
                appendLine()
            }
        }

        append("}").appendLine().appendLine()
        append("operator fun I18NBundle.get(key: I18NKey): String = this[key.key]").appendLine()
        appendLine()
        append("operator fun I18NBundle.get(key: I18NKey, vararg args: Any): String = this.format(key.key, *args)").appendLine()
    }

    if (i18nKeyFile.exists()) {
        i18nKeyFile.delete()
    }
    i18nKeyFile.createNewFile()
    i18nKeyFile.writeText(content)
}
