package io.github.masamune.tiledmap

import io.github.masamune.combat.effect.*

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class ActionType(private val actionFactory: () -> Effect) {
    ATTACK_SINGLE(::AttackSingleEffect),
    FIREBALL(::FireballEffect),
    FIREBOLT(::FireboltEffect),
    UNDEFINED({ DefaultEffect }),
    ;

    operator fun invoke() = actionFactory()
}
