package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class ConsumableType {
    COMBAT_AND_INVENTORY,
    COMBAT_ONLY,
    INVENTORY_ONLY,
    UNDEFINED;
}
