package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class ItemCategory {
    ACCESSORY,
    ARMOR,
    BOOTS,
    HELMET,
    OTHER,
    QUEST,
    WEAPON;
}
