package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class ItemType {
    BOOTS,
    BOOTS_SPEED,
    CHAIN_MAIL,
    ELDER_SWORD,
    HELMET,
    INTELLIGENCE_POTION,
    MAGIC_VEST,
    RING,
    SCROLL_INFERNO,
    SMALL_HEALTH_POTION,
    SMALL_MANA_POTION,
    SMALL_STRENGTH_POTION,
    STUDDED_LEATHER,
    SWORD_HEAL,
    SWORD_STRENGTH,
    TEREALIS_FLOWER,
    UNDEFINED;
}
