package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class ItemType {
    BOOTS,
    ELDER_SWORD,
    HELMET,
    RING,
    SCROLL_INFERNO,
    SMALL_HEALTH_POTION,
    SMALL_MANA_POTION,
    SMALL_STRENGTH_POTION,
    STUDDED_LEATHER,
    TEREALIS_FLOWER,
    UNDEFINED;
}
