package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
open class TiledStats(
    var agility: Float = 0f,
    var arcaneStrike: Float = 0f,
    var armor: Float = 0f,
    var constitution: Float = 0f,
    var criticalStrike: Float = 0f,
    var damage: Float = 0f,
    var intelligence: Float = 0f,
    var life: Float = 0f,
    var lifeMax: Float = 0f,
    var magicalEvade: Float = 0f,
    var mana: Float = 0f,
    var manaMax: Float = 0f,
    var physicalEvade: Float = 0f,
    var resistance: Float = 0f,
    var strength: Float = 0f
) {
    fun isAllNull(): Boolean {
        return agility == 0f
            && arcaneStrike == 0f
            && armor == 0f
            && constitution == 0f
            && criticalStrike == 0f
            && damage == 0f
            && intelligence == 0f
            && life == 0f
            && lifeMax == 0f
            && magicalEvade == 0f
            && mana == 0f
            && manaMax == 0f
            && physicalEvade == 0f
            && resistance == 0f
            && strength == 0f
    }

    override fun toString(): String {
        return "TiledStats(agility=$agility, arcaneStrike=$arcaneStrike, armor=$armor, constitution=$constitution, criticalStrike=$criticalStrike, damage=$damage, intelligence=$intelligence, life=$life, lifeMax=$lifeMax, magicalEvade=$magicalEvade, mana=$mana, manaMax=$manaMax, physicalEvade=$physicalEvade, resistance=$resistance, strength=$strength)"
    }

    companion object {
        val NULL_STATS = TiledStats()
    }

}
