package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
data class TiledStats(
    val agility: Float = 0f,
    val arcaneStrike: Float = 0f,
    val armor: Float = 0f,
    val constitution: Float = 0f,
    val criticalStrike: Float = 0f,
    val damage: Float = 0f,
    val intelligence: Float = 0f,
    val life: Float = 0f,
    val lifeMax: Float = 0f,
    val magicalEvade: Float = 0f,
    val mana: Float = 0f,
    val manaMax: Float = 0f,
    val physicalEvade: Float = 0f,
    val resistance: Float = 0f,
    val strength: Float = 0f
) {
    fun isAllNull(): Boolean {
        return agility == 0f
            && arcaneStrike == 0f
            && armor == 0f
            && constitution == 0f
            && criticalStrike == 0f
            && damage == 0f
            && intelligence == 0f
            && life == 0f
            && lifeMax == 0f
            && magicalEvade == 0f
            && mana == 0f
            && manaMax == 0f
            && physicalEvade == 0f
            && resistance == 0f
            && strength == 0f
    }
}
