package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class TiledObjectType {
    ELDER,
    ENEMY,
    FLOWER_GIRL,
    HERO,
    MERCHANT,
    PORTAL,
    SMITH,
    UNDEFINED
}
