package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
data class TiledStats (
    val agility: Float = 0f,
    val armor: Float = 0f,
    val intelligence: Float = 0f,
    val magicalDamage: Float = 0f,
    val physicalDamage: Float = 0f,
    val resistance: Float = 0f,
    val strength: Float = 0f
)
