package io.github.masamune.tiledmap

// This is an autogenerated class by gradle's 'genTiledEnumsAndExtensions' task. Do not touch it!
enum class TiledObjectType {
    BUTTERFLY,
    ELDER,
    FLOWER_GIRL,
    HERO,
    ITEM,
    LARVA,
    MERCHANT,
    MUSHROOM,
    PORTAL,
    SMITH,
    TRIGGER,
    UNDEFINED;
}
